# Generated by Django 3.0.5 on 2020-04-25 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0003_auto_20200425_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser',
            new_name='Person',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
