# Generated by Django 3.0.5 on 2020-04-25 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0005_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(null=True, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
