# Generated by Django 3.0.5 on 2020-04-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20200425_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_number',
        ),
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
