# Generated by Django 3.0.5 on 2020-04-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
