# Generated by Django 3.0.5 on 2020-04-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
