# Generated by Django 3.0.5 on 2020-04-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiz', '0002_vacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
