# Generated by Django 3.0.5 on 2020-04-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiz', '0004_vacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
